export default images = {
    LOGO: require('../assets/images/logo.png'),
    LOGO_MONO_GREEN: require('../assets/images/ecocity@1.png'),
    LOGO_MONO_WHITE: require('../assets/images/ecocity-white@1.png'),
    MAP_MARKER:  require('../assets/images/map-marker@1.png'),
    MENU:  require('../assets/images/menu.png'),
    BELL:  require('../assets/images/bell@1.png'),
    SCAN_BUTTON:  require('../assets/images/circle-scan-button@1.png'),
    HELP_BUTTON:  require('../assets/images/circle-help-button@1.png'),
    LOCATE_BUTTON:  require('../assets/images/circle-location-button@1.png'),
    REFRESH_BUTTON:  require('../assets/images/circle-refresh-button@1.png'),
    SCOOTER_ICON:  require('../assets/images/scooter-icon@1.png'),
    SCOOTER_DRAW:  require('../assets/images/scooter_drawx1.png'),
    ROUTE_ICON:  require('../assets/images/route-icon@1.png'),
    BACK_BUTTON: require('../assets/images/back-button1@1.png'),
    DISTANCE_ICON: require('../assets/images/distance-icon1.png'),
    DURATION_ICON: require('../assets/images/duration-icon1.png'),
    OVERLAY_SCAN: require('../assets/images/scan-overlay1.png'),
    BIKE_ICON: require('../assets/images/bike-icon1.png'),
    BUTTON_CODE: require('../assets/images/button-place-code1.png'),
    BUTTON_LIGHT: require('../assets/images/button-light1.png'),
    BUTTON_LIGHT_ON: require('../assets/images/button-light-on1.png'),
    BUTTON_CLOSE: require('../assets/images/button-close_11.png'),
    SCAN_QR: require('../assets/images/scan_qr.png'),
    CAMERA_ICON: require('../assets/images/camera-pic1.png'),
}
